services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wextai-be.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - /env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web